### ISSUE TITLE
Cross publish for Scala 3

### ISSUE THREAD

**Issue by andreamarcolin** [VladKopanev/cats-saga#100]
Hi! I was wondering if there are any plans to cross publish cats-saga for Scala 3 or if there is any major road-blocker.
I could happily spare some time if you need help. 

Thanks for this library and your efforts!

**Comment by VladKopanievExt** [comment]
Hi @andreamarcolin ! Thanks for the feedback ! I'm not sure what could stop us from cross-publishing it for Scala 3, only lack of my time, so if you can help me with this issue I would really appreciate that!

**Comment by VladKopanev** [comment]
Hi @andreamarcolin ! Thanks for the feedback ! I'm not sure what could stop us from cross-publishing it for Scala 3, only lack of my time, so if you can help me with this issue I would really appreciate that!

**Comment by andreamarcolin** [comment]
Spent some time a couple days ago fiddling and trying to make cats-saga compile without much luck, and I figured the first thing stopping this could be cats-retry not yet published for Scala 3, so I started from there (PR linked above)!
