### ISSUE TITLE
Consider providing a non-concurrent Saga

### ISSUE THREAD

**Issue by LukaJCB** [VladKopanev/cats-saga#42]
Having support for parallel execution is great! However it comes at the cost of requiring `Concurrent` for transacting a Saga. Possibly there could be a version of Saga which doesn't need `Concurrent` and could support types like doobie's `ConnectionIO`.

**Comment by VladKopanev** [comment]
I think you are right. I also thought that this `Concurrent` requirement is a design flaw, but the solution was not obvious for me at that time. Thanks for this idea, I think we should try to implement it!

**Comment by benhutchison** [comment]
This is biting me because I also use MTL MonadState in the `F` stack, and there's no `StateT` instance for Concurrent. The lack of StateT+Concurrent is, IIUC, because if the Concurrent forks Fibers, state updates would have to be discarded on all but one of the branches.

**Comment by VladKopanev** [comment]
@benhutchison could you please look at my PR https://github.com/VladKopanev/cats-saga/pull/51 ? It moves Concurrent typeclass requirement to Saga methods that actually meant to do parallel composition.
