### ISSUE TITLE
Cats Effect 3 support

### ISSUE THREAD

**Issue by TimWSpence** [VladKopanev/cats-saga#88]
Hi! Just wondering if you have plans to support cats effect 3? I can attempt to find some time to assist if necessary :)

**Comment by VladKopanev** [comment]
Hi @TimWSpence! I think that's a great idea! But unfortunately, I'll be busy till the mid of May. If you would like to contribute to this project then go ahead, I will appreciate any help from you!

**Comment by TimWSpence** [comment]
No worries @VladKopanev! No guarantees but I'll do my best to find some time :)

**Comment by TimWSpence** [comment]
Just noting that there is a dependency on https://github.com/cb372/cats-retry/pull/305 being released

**Comment by VladKopanev** [comment]
> Just noting for the sake of tracking that there is a dependency on [cb372/cats-retry#305](https://github.com/cb372/cats-retry/pull/305) being released

I think they just merged the support for CE 3, but it's not yet released. I don't see new releases in maven-central. Let's hope it's gonna be released soon then.

**Comment by andreamarcolin** [comment]
cats-retry 3.0.0 with support for CE3 has been released! 🎉 

I'm also interested in having a CE3 compatible cats-saga release :)

**Comment by VladKopanev** [comment]
@andreamarcolin great! Thanks for the heads-up! I started migrating the code now, I will need some time because there are changes in Fibers semantics and we have not so trivial code for parallel Sagas, but I'm working on it.

**Comment by VladKopanev** [comment]
@TimWSpence @andreamarcolin cats-effect 3 support was merged into main 🍾 🥳 . But before I create a new major release I want to make more improvements to library design and expand on SagaInterpreter thing, so it would be easy to create custom interpreters and we will also see Scala 3 support. Not gonna close this task until the release is done though, so please stay tuned.

**Comment by andreamarcolin** [comment]
Hey @VladKopanev! Did #105 closed #102 this or are you planning to add anything else before 1.x.x?
When it comes to Scala 3 support, cats-retry is unlikely to provide us with a release soon enough (my PR is stuck waiting for approval to run GitHub Actions workflows, tried to tag authors and asked on Typelevel's Discord server, without luck).
So I was wondering, would a cats-saga 1.0.0-M1 or RC1 make sense while we wait for it? It would definitely help at least me in trying to migrate projects I'm working on to CE3, while the Scala 3 migration will come later.

Thanks!

**Comment by VladKopanev** [comment]
Hi @andreamarcolin I understand your concern here, I will try to schedule some time this month to produce a CE3 compatible release then so you won't need to wait until cats-retry is bumped

**Comment by VladKopanev** [comment]
@andreamarcolin @TimWSpence 

Hey folks, good news, I've finally released version 1.0.0-RC1 which includes CE-3 support! 

Please try it out and let me know if you have any issues.

Thank you for you support and patience 🙏 

https://search.maven.org/artifact/com.vladkopanev/cats-saga_2.13/1.0.0-RC1/jar
